language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
   - npm config set loglevel warn
   - "npm install"
before_script:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - npm prune
  - npm run build:docker
  - npm run start:docker
script:
  - npm run lint
  - npm run test
  - npm run test:nsp
after_failure:
  - docker ps
  - docker-compose logs
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_script:
  - npm run stop:docker